### ISSUE TITLE
Change homepage homepage icon to lil cat tooting

### ISSUE THREAD

**Issue by lynncyrin** [TootCat/mastodon#1]

**Comment by lynnco** [comment]
s/icon/image

the one here https://toot.cat/about

**Comment by iangreenleaf** [comment]
🐈💨

**Comment by ubiquill** [comment]
@witchprincess@witches.town agreed to draw us a logo. I'm thinking a kitten in a mastodon kigurumi 😄

**Comment by lynnco** [comment]
I'd love that! it was exactly what I was thinking of

**Comment by wavebeem** [comment]
nice

**Comment by ashyon** [comment]
sweet!

**Comment by ashyon** [comment]
My girlfriend is drawing us a replacement image for the getting started column btw, when she's done I'll post it here and you all can say what you think.

**Comment by EmilePouget** [comment]
Isn't this what the favicon is right now?

Then there's an improvement suggestion I have: the background shouldn't be plain white but rather transparent.

**Comment by wavebeem** [comment]
Maybe it looks better on a retina screen but on a normal density one I can't even tell what the image is supposed to be either. I could probably do some cleanup on the icon to make it a bit more legible at smaller sizes, including removing the white square background.
