### ISSUE TITLE
Theme reversion and re-appraisal

### ISSUE THREAD

**Issue by lynncyrin** [TootCat/mastodon#17]
The new pink toned theme is quite a lot harder for me to see, and I saw at least one other person have an issue with it. I'd like the theme change to be reverted (back to mastodon's basic setup) on a11y grounds, and re-proposed but given at least a few days for feedback and updates.

**Comment by ubiquill** [comment]
Yeah I tend to agree. Feel free to revert. I don't know if I'll have time
today

**Comment by wavebeem** [comment]
Yeah, if people are having a harder time reading it, I think we need to undo it. We could just revert the colors but keep the new graphics though? @ashyon should just be a change to the variables.scss file right?

**Comment by ashyon** [comment]
Yeah if it's an issue then I have no problem undoing it. @wavebeem yeah just revert the variables.scss and it'll all switch back. I think I also changed the logo/icon color so revert the svg and png for that as well.

**Comment by ashyon** [comment]
I'm thinking to start work on a theme selector so that users have more control over their experience anyway.

**Comment by wavebeem** [comment]
Do you wanna do the revert? I can take a look at it tonight probably like 7 or 8 otherwise.

**Comment by lynnco** [comment]
I brought my hobby dev laptop with me to work today, so I can get it done @ 1230

**Comment by ashyon** [comment]
Reverted the change. Ready to deploy.

**Comment by ubiquill** [comment]
the bottom of the production guide has the instructions for updating. After doing the git changes the important steps are gonna be:

RAILS_ENV=production bundle exec rails assets:precompile

and

sudo systemctl restart mastodon-*.service

**Comment by ashyon** [comment]
Who has SSH access and can deploy the changes?

**Comment by wavebeem** [comment]
I don't have my key on my work laptop so I can't until I get home.

**Comment by lynnco** [comment]
I do, I'll deploy in the next hour

**Comment by ashyon** [comment]
Cool :3

**Comment by lynnco** [comment]
I'll be reverting to immediately before the theme merge, so this commit https://github.com/TootCat/mastodon/commit/b2f393089d0347f601bced03f52e96098a0b92d4

**Comment by ashyon** [comment]
I already did a revert commit so you can just pull that

**Comment by ashyon** [comment]
That way we'll still have the commits from afterward @lynnco

**Comment by lynnco** [comment]
oh, this one? I assumed from the name that it only reverted the logo and not also the theme color https://github.com/TootCat/mastodon/commit/430f9269d5c007196e41d2fddc85a19a9c4f6d92

**Comment by ashyon** [comment]
Yeah I had forgotten to commit the theme color before I changed the logo so they were both in the same commit

**Comment by lynnco** [comment]
Resolved! We can start re-appraising the theme change as a seperate issue
