### ISSUE TITLE
Compose box does not appear in mobile view

### ISSUE THREAD

**Issue by ubiquill** [TootCat/mastodon#21]
after the most recent UI tweaks  I can no longer see the compose area in the mobile view. I checked on Mastodon.social and I can still see it there. So, this appears to be one of our changes.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by wavebeem** [comment]
Oh no. Definitely happening for me too.

**Comment by ubiquill** [comment]
is fixed now

**Comment by ashyon** [comment]
Sorry bout that, my fault
