### ISSUE TITLE
Set favicon to a branded image

### ISSUE THREAD

**Issue by polymerwitch** [TootCat/mastodon#22]
This image was suggested as a possibility: https://www.goodfreephotos.com/vector-images/black-cat-with-big-head-vector-clipart.png.php

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by ashyon** [comment]
We could use that but maybe change the color? If it's still black it's easy to get lost with the other favicons in your tab bar...

**Comment by wavebeem** [comment]
Sticking it on a white background would help too. I could help with that if
needed.

**Comment by polymerwitch** [comment]
Set the favicon to dabcat
