### ISSUE TITLE
toot.cat translation guide :p

### ISSUE THREAD

**Issue by lynncyrin** [TootCat/mastodon#26]
because its not immediately obvious what

- boops
- meows
- baps

are

**Comment by wavebeem** [comment]
yeahh they are very cute terms but definitely kind of confusing. we're walking a line with them imo.

**Comment by lynnco** [comment]
Actually, alternative suggestion, we shouldn't use terms whose meanings aren't immediately obvious, and "baps" definitely counts as that

**Comment by polymerwitch** [comment]
maybe we should change the alt-text to be standard?

Just as a note: I left all of the report, block, mute terms alone. As I don't want people to get confused.

**Comment by polymerwitch** [comment]
another idea, create a feline language file. Then have all the terms switched there.

**Comment by wavebeem** [comment]
Heheh, I kinda like that idea! It could be a fork of English. Then users can easily opt-out.
