### ISSUE TITLE
5/1 incident report

### ISSUE THREAD

**Issue by lynnco** [TootCat/mastodon#30]
(will write it later)

**Comment by lynnco** [comment]
in abstract, there was an issue involving 3 users

- user_1@instance_a made a post
- user_2@instance_b replied to the post with harassment
- user_3@instance_b is an admin of instance_b, and more or less furthered the harassment user_2@instance_b started

toot.cat took these actions

- silenced user_2@instance_b and user_3@instance_b
- domain silenced instance_b
- expressed its support for user_1@instance_a

**Comment by lynnco** [comment]
It's unclear to me whether or not me obfuscating identities is a good policy, so I'm open to feedback on that

**Comment by polymerwitch** [comment]
since this is public I think it very much should be obfuscated. I'm not even sure that github is the best place to keep reports. I hear you may know of a better place to keep incident reports though ...
