### ISSUE TITLE
revamp of the nudity / sex / kinky rules for toot.cat

### ISSUE THREAD

**Issue by lynnco** [TootCat/mastodon#36]
I just had a meeting with @thetinkerfae and we came up with this proposal for the rules regarding nudity / sex / kink. We suggested the CoC be edited to include the following:

---

Nudity is allowed without a CW as long as no genitals or nipples are shown
* If they are visible in the image they must be censored
* Nipple censoring pertains to any gender

Any sexual imagery must be hidden as a sensitive image
* Sexual imagery is considered to be any sex / kink act regardless of clothing state / nudity
* Sexual imagery and nudity are distinct concepts
* No illegal imagery is allowed regardless of CW state

Nudity / imagery of sex / kink acts with a CW do not need to be censored in any way

Nudity / imagery of sex / kink acts should not have other users tagged without their explicit prior consent

Violation content warning rules will 
* An immediate silence when its violated on the federation timeline
* A domain silence when its violated by multiple parties on an instance
* A warning and admin editing your content when its violated by toot.cat users

Posting nudity / imagery of sex / kink acts that is not of yourself needs to include attribution to the person(s) visible, in such a way that clearly expresses their consent to have that imagery posted

Violation of the consent to post rule will result in
* An immediate suspension when its violated on the federation timeline
* A domain suspension when its violated by multiple parties on an instance
* (1) warning, followed by account deletion when its violated by toot.cat users

toot.cat supports and invites sex workers to join our community and will not tolerate any harassment or slurs made at or about sex workers (ie: prostitute, hooker, whore)

**Comment by saper** [comment]
Question: Why nipples are special? Is this a U.S.-only tradition?

**Comment by lynnco** [comment]
@saper it is a cultural norm present in the US

**Comment by polymerwitch** [comment]
this is probably covered by just general anti-oppression statements, but maybe it would be worth calling out that DMing uninvited sexual images to someone is a nono. Similarly with gore photos.

**Comment by lynnco** [comment]
Ah yea, I haven't considered the "users mentioned" axis for this issue. I may want to add a sub-section about that, explicitly

**Comment by aeschright** [comment]
If you're going to say "illegal" you need to define a jurisdiction, since users come from many parts of the world.

**Comment by lynnco** [comment]
```diff
- No illegal imagery is allowed regardless of CW state
+ No illegal imagery is allowed regardless of CW state, where the legality of an image is defined by the laws in the primary jurisdiction of the admins (Portland, Oregon, USA)
```

although this makes me wish most of us were in New Zealand, which has better laws about things like this

**Comment by saper** [comment]
So Oregon has laws prohibiting bare male nipples? wow

**Comment by lynnco** [comment]
@saper I can't tell if your comment is a joke or not

but for the sake of information, no, Oregon does not have laws prohibiting bare male nipples.

The law in Portland, Oregon is here https://www.portlandoregon.gov/citycode/article/15423?

**Comment by saper** [comment]
No, I was genuinely curious.

So this law prohibits exposure of genitalia (breats aren't) in a public space, which is not what we are doing here. Thank you.

**Comment by lynnco** [comment]
added to https://github.com/TootCat/mastodon/wiki/Code-of-Conduct
