### ISSUE TITLE
Rule proposal about tech posts

### ISSUE THREAD

**Issue by lynncyrin** [TootCat/mastodon#37]
from: https://toot.cat/@cyrinsong/457805

---

moderation suggestion!

Due to overwhelming feedback about Mastodon's skew towards tech, to the exclusion of other industries and cultures, I have a suggestion. Posts about tech (ex: the source of a python script you wrote) should have a "Tech" (or otherwise context specific) CW, so that people who aren't programmers can be on Mastodon without their TL being 70% (subjectively) unreadable and untranslatable* source code

* ie I can translate Spanish to English, but not Python to English

**Comment by polymerwitch** [comment]
Along with source code we should also list "toots that are purely technical in nature".

For example, I've tooted things like "I think the delayed messages we are seeing are from some of the sidekiq queues on other instances not being tuned with enough workers". While it doesn't contain source code I could see that leaving non-tech users out of the conversation.

**Comment by lynnco** [comment]
That would also be a good post to follow up with a non CWed version that's something like "the servers are having problems connecting to other instances! messages will be delayed for a while" in plain text
