### ISSUE TITLE
federation alliance feature request

### ISSUE THREAD

**Issue by lynncyrin** [TootCat/mastodon#38]
here: https://toot.cat/@cyrinsong/462882

I need to take the time to write it up as a feature request on mastodon-core

**Comment by lynnco** [comment]
alliances should almost definitely be called herds

**Comment by lynncyrin** [comment]
I'm closing a bunch of my older github issues ♻️  feel free to open a new issue describing this same change! Or re-open this one, if someone is still interested in working on it 📝
