### ISSUE TITLE
investigate if users on suspended instances can still see your toots

### ISSUE THREAD

**Issue by lynncyrin** [TootCat/mastodon#40]
[Issue text goes here].

* * * *

- [ ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by strand** [comment]
Can they?

**Comment by lynnco** [comment]
oh, I dunno. I'm not sure why I closed this either

**Comment by lynnco** [comment]
closing github issues on my sleep over here

**Comment by lynncyrin** [comment]
I'm closing a bunch of my older github issues ♻️  feel free to open a new issue describing this same change! Or re-open this one, if someone is still interested in working on it 📝
