### ISSUE TITLE
(black / white)list terminology alternatives!

### ISSUE THREAD

**Issue by lynncyrin** [TootCat/mastodon#43]
they should be the same length, and present a (yes / no) dichotomy

5 chars is preferred as that's the current length

(6 chars)
- permit / reject

**(5 chars)**
- allow / block (a "blocklist" term is likely already in use)

(4 chars)
- safe / deny
- auth / deny (hard to say out loud)

(2 chars)
- go / no

**Comment by bit-mancer** [comment]
2 chars!

go / no

(golist/nolist sort of rolls off the tongue, but they're so short I'm not sure how descriptive/useful these would actually be...)

**Comment by jonpincus** [comment]
How important is it that they be the same length?  Access Control Lists (ACLs) often use **allow** and **deny**.  

If it is important for them to be the same length, I would go with **allow** and *block*.  "Safe" gives the wrong impression - it's more confident than is warranted in most situations.

**Comment by lynnco** [comment]
Them being the same length is primarily useful for refactoring, in that it will mean a much smaller diff in effected code.

I added a note about 5 letter combos being preferred for that same reason

**Comment by jonpincus** [comment]
Thinks to self: how does that work from an internationalization perspective?

But, okay, it is what it is.  It sounds like allow/block is the best bet.  And as an added bonus, it will work for the Oulipians!

**Comment by wavebeem** [comment]
I still think allow/deny is best... how is the length going to affect the diff?

**Comment by mkzero** [comment]
Why would you replace the well-known terminology though? This issue has no word about the *why*...?

**Comment by jonpincus** [comment]
Because it has racialized overtones - black = bad, keep them out!  white = everything is cool.

It's a great example of an unintentional microagression embedded in the code (and the language we use for the software), so I'm all in favor of changing it.

**Comment by mkzero** [comment]
How racist could you be, to say "black = bad"? And what kind of mindset makes you think supporting that definition will make it less valid?

**Comment by strand** [comment]
Folks find these terms offensive @mkzero. You may not, but others do, and it's disrespectful to feign doubt about their judgment.

**Comment by strand** [comment]
As long are the terms are consistent, I don't think the specific choice is that important. 

That being said I prefer blocklist and safelist, because they are self evidently descriptive.

**Comment by mkzero** [comment]
> Folks find these terms offensive @mkzero. You may not, but others do, and it's disrespectful to feign doubt about their judgment.

But don't you see how seeing those as offensive is only possible by thinking like a racist?

> prefer blocklist and safelist, because they are self evidently descriptive

What is a safelist, though? Does it save things to memory? Probably "things that are safe to use"? What is safe to use? Whitelists aren't inherently "safe", they are just lists compiled of items an operator always wants to pass. For that matter and by that logic it'd be "blocklist" and "passlist" which just sounds horrific and might trigger those not able to obtain a passport(like people from oppressive countries that don't allow citizens to leave the country).

**Comment by iangreenleaf** [comment]
@mkzero serious question: why are you putting so much effort into arguing with people on the internet to keep these terms? They are made-up words in the first place, used out of their original context, with equal or lesser explanatory power than most of the proposed alternatives. Why is it so important to you that we keep the old terms?

**Comment by strand** [comment]
Given that @mkzero's [only comments on tootcat/mastodon issues](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aopen+is%3Aissue+commenter%3Amkzero+repo%3Atootcat%2Fmastodon) are contradicting that an issue created by a maintainer is in fact an issue, I would characterize  their behavior as trolling. If @mkzero wants to contribute to the project, they can, but they haven't been adding any useful to the conversations yet.

**Comment by mkzero** [comment]
@iangreenleaf because as a non-native English speaker with a lot of friends who have less advanced English skills I know the difficulties of people using other terms than those already established. And as I pointed out in my comment above, these proposed alternatives aren't necessarily self-explaining or trouble-free. The initial issue was someone voicing racism and now you don't even see who changing well-known terms to others might give non-native speakers problems actually understanding, thus *excluding* them. 

@strand Trolling is a derogatory term used to describe different kinds feedback. I'd rather not you discriminate my choice of wording as such, especially when your only apparent goal is to use it as a rethoric method of invalidating my comments.

**Comment by iangreenleaf** [comment]
@mkzero if your primary motivation in arguing this is concern for non-native English speakers, shouldn't we be able to find you arguing elsewhere on the web with equal fervor against terms like "monad", "monkey patch", "duck typing", "splat", "comprehensions", "tweet", "googling", "alt-right", "flash mob", "torrent", and "podcast"? After all, these are words that are relatively new, have poor explanatory power, and offer no clues to their meaning to people who are unfamiliar with their usage. Seems like you should be at least as fired up about those as you are about this change.

**Comment by lynnco** [comment]
Without having to get into the definition of "trolling" - the way that you are commenting on our issues @mkzero is not sparking productive discussions. Please take a break from commenting in this repo, in the interest of having all of us doing more productive work in our free time.

**Comment by mkzero** [comment]
@iangreenleaf Those are new words, which are adopted a lot faster, not words that have been in a similar use for several hundred years and which permeated through different languages in one way or another. Take German or Russian for example - the translation for blacklist is literal in both, meaning you can translate "blacklist" with basic vocabulary to the direct translation of that *exact* meaning. 

@lynnco So you do argue, that you have more productive things to do yet have no intention to listen someone who has actual knowledge of multiple languages and background knowledge of etymology and linguistics? I'm sorry, but that's just contradictory.

**Comment by strand** [comment]
Disappointed that this issue was not responded to by a maintainer.

**Comment by lynncyrin** [comment]
It's not clear from this github issue, but none of us have worked on this since 2017. There's not a whole lot we (the people who started this thread) can do here 
![image](https://user-images.githubusercontent.com/5768468/63293486-0ad5e000-c27d-11e9-9f87-c0c863684fd4.png)

**Comment by lynncyrin** [comment]
It's also not even clear if https://toot.cat/ is actually even connected to this github repository anymore 🤷‍♀
