### ISSUE TITLE
CoC updates for ableism

### ISSUE THREAD

**Issue by lynncyrin** [TootCat/mastodon#50]
WIP

**Comment by lynnco** [comment]
will end up looking similar to https://github.com/TootCat/mastodon/issues/36

**Comment by lynnco** [comment]
inspired by https://toot.cat/@cripcat/963874

**Comment by lynncyrin** [comment]
I'm closing a bunch of my older github issues ♻️  feel free to open a new issue describing this same change! Or re-open this one, if someone is still interested in working on it 📝
